const S={progress:JSON.parse(localStorage.getItem("sam-progress")||"{}")};let course;
async function load(){course=await fetch("./content/en/course.json",{cache:"no-store"}).then(r=>r.json());home()}
function save(){localStorage.setItem("sam-progress",JSON.stringify(S.progress))}
function shell(body,tab="home"){document.querySelector("#app").innerHTML='<main class="app">'+body+'</main><nav class="bottom"><div class="bottomin"><button class="nav '+(tab==="home"?"on":"")+'" data-go="home">⌂ Главная</button><button class="nav '+(tab==="words"?"on":"")+'" data-go="words">▤ Слова</button><button class="nav '+(tab==="train"?"on":"")+'" data-go="train">✓ Тренажёр</button></div></nav>';bind()}
function bind(){document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>({home,words,train}[x.dataset.go]()));document.querySelectorAll("[data-lesson]").forEach(x=>x.onclick=()=>lesson(x.dataset.lesson))}
function home(){let done=Object.values(S.progress).filter(Boolean).length,p=Math.round(done/course.lessons.length*100);shell('<div class="top"><div class="brand">Самоучитель</div><span class="badge">EN • A1</span></div><section class="hero"><h1>English с нуля</h1><p>Короткие уроки, живые фразы и повторение.</p><div class="progress"><i style="width:'+p+'%"></i></div><small>'+p+'% пройдено</small></section><div class="grid"><div class="card" data-go="words"><span class="icon">🔊</span><b>Слова</b><small class="muted">слушать и учить</small></div><div class="card" data-go="train"><span class="icon">🧠</span><b>Тренажёр</b><small class="muted">проверить себя</small></div><div class="card"><span class="icon">🎧</span><b>Прослушка</b><small class="muted">следующий модуль</small></div><div class="card"><span class="icon">📈</span><b>Прогресс</b><small class="muted">'+done+' уроков</small></div></div><div class="section"><h2>Первые уроки</h2></div>'+course.lessons.map((l,i)=>'<div class="lesson" data-lesson="'+l.id+'"><div class="num">'+(i+1)+'</div><div><b>'+l.title+'</b><br><small>'+l.subtitle+'</small></div></div>').join(""))}
function speak(t){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}
function word(w){return '<div class="word"><div class="wordline"><div><div class="en">'+w.en+'</div><div class="ru">'+w.ru+'</div></div><button class="speaker" data-say="'+w.en+'">▶</button></div><small class="muted">'+w.example+'</small></div>'}
function lesson(id){let l=course.lessons.find(x=>x.id===id);shell('<button class="back" id="back">← Назад</button><h1>'+l.title+'</h1><p class="muted">'+l.explain+'</p>'+l.words.map(word).join("")+'<button class="btn" id="done">Завершить урок</button>');document.querySelector("#back").onclick=home;document.querySelectorAll("[data-say]").forEach(x=>x.onclick=()=>speak(x.dataset.say));document.querySelector("#done").onclick=()=>{S.progress[id]=true;save();home()}}
function words(){let a=course.lessons.flatMap(x=>x.words),s=new Set();a=a.filter(x=>!s.has(x.en)&&(s.add(x.en),true));shell('<h1>Слова и фразы</h1><p class="muted">Нажмите ▶ для произношения.</p>'+a.map(word).join(""),"words");document.querySelectorAll("[data-say]").forEach(x=>x.onclick=()=>speak(x.dataset.say))}
function train(){let a=course.lessons.flatMap(x=>x.words),q=a[Math.floor(Math.random()*a.length)],o=[q,...a.filter(x=>x.en!==q.en).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell('<h1>Тренажёр</h1><p class="muted">Выберите перевод</p><h2>'+q.en+'</h2>'+o.map(x=>'<button class="word" style="width:100%;text-align:left" data-answer="'+(x===q)+'">'+x.ru+'</button>').join("")+'<br><button class="btn" id="next">Следующий</button>',"train");document.querySelectorAll("[data-answer]").forEach(x=>x.onclick=()=>{x.style.background=x.dataset.answer==="true"?"#dcfce7":"#fee2e2"});document.querySelector("#next").onclick=train}
load();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");