const S={progress:JSON.parse(localStorage.getItem("sam-progress")||"{}"),settings:JSON.parse(localStorage.getItem("sam-settings")||'{"theme":"light","font":100}'),drill:new Set(JSON.parse(localStorage.getItem("sam-drill")||"[]")),learned:new Set(JSON.parse(localStorage.getItem("sam-learned")||"[]"))};let course,dictionary,school;
function applySettings(){document.documentElement.dataset.theme=S.settings.theme;document.documentElement.style.fontSize=S.settings.font+"%"}
async function load(){applySettings();[course,dictionary,school]=await Promise.all([fetch("./content/en/course.json",{cache:"no-store"}).then(r=>r.json()),fetch("./content/en/dictionary.json",{cache:"no-store"}).then(r=>r.json()),fetch("./content/en/school.json",{cache:"no-store"}).then(r=>r.json())]);home()}
function save(){localStorage.setItem("sam-progress",JSON.stringify(S.progress))}
function saveSettings(){localStorage.setItem("sam-settings",JSON.stringify(S.settings));applySettings()}function saveDictionaryState(){localStorage.setItem("sam-drill",JSON.stringify([...S.drill]));localStorage.setItem("sam-learned",JSON.stringify([...S.learned]))}
function shell(body,tab="home"){document.querySelector("#app").innerHTML='<main class="app">'+body+'</main><nav class="bottom"><div class="bottomin"><button class="nav '+(tab==="home"?"on":"")+'" data-go="home">⌂ Главная</button><button class="nav '+(tab==="words"?"on":"")+'" data-go="words">▤ Слова</button><button class="nav '+(tab==="train"?"on":"")+'" data-go="train">✓ Тренажёр</button></div></nav>';bind()}
function bind(){document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>({home,words,train,dictionaryView,schoolView}[x.dataset.go]?.()));document.querySelectorAll("[data-lesson]").forEach(x=>x.onclick=()=>lesson(x.dataset.lesson))}
function home(){let done=Object.values(S.progress).filter(Boolean).length,p=Math.round(done/course.lessons.length*100);shell('<div class="top"><div class="brand">Самоучитель</div><div class="topactions"><span class="badge">EN • A1</span><button class="gear" id="settings" aria-label="Настройки">⚙</button></div></div><section class="hero"><h1>English с нуля</h1><p>Короткие уроки, живые фразы и повторение.</p><div class="progress"><i style="width:'+p+'%"></i></div><small>'+p+'% пройдено</small></section><div class="grid"><div class="card" data-go="schoolView"><span class="icon">🏫</span><b>Школа</b><small class="muted">1–11 классы</small></div><div class="card" data-go="dictionaryView"><span class="icon">📚</span><b>Словарь</b><small class="muted">база слов по уровням</small></div><div class="card" data-go="words"><span class="icon">🔊</span><b>Слова</b><small class="muted">слушать и учить</small></div><div class="card" data-go="train"><span class="icon">🧠</span><b>Тренажёр</b><small class="muted">проверить себя</small></div><div class="card"><span class="icon">🎧</span><b>Прослушка</b><small class="muted">следующий модуль</small></div><div class="card"><span class="icon">📈</span><b>Прогресс</b><small class="muted">'+done+' уроков</small></div></div><div class="section"><h2>Первые уроки</h2></div>'+course.lessons.map((l,i)=>'<div class="lesson" data-lesson="'+l.id+'"><div class="num">'+(i+1)+'</div><div><b>'+l.title+'</b><br><small>'+l.subtitle+'</small></div></div>').join(""));document.querySelector("#settings").onclick=settings}
function speak(t){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}
function word(w){return '<div class="word"><div class="wordline"><div><div class="en">'+w.en+'</div><div class="pron">'+(w.pronunciationRu||"")+'</div><div class="ru">'+w.ru+'</div></div><button class="speaker" data-say="'+w.en.replaceAll('"',"&quot;")+'">▶</button></div><small class="muted">'+w.example+'</small></div>'}
function wireSpeak(){document.querySelectorAll("[data-say]").forEach(x=>x.onclick=()=>speak(x.dataset.say))}
function lesson(id){let l=course.lessons.find(x=>x.id===id);shell('<button class="back" id="back">← Назад</button><h1>'+l.title+'</h1><p class="muted">'+l.explain+'</p>'+l.words.map(word).join("")+'<button class="btn" id="done">Завершить урок</button>');document.querySelector("#back").onclick=home;wireSpeak();document.querySelector("#done").onclick=()=>{S.progress[id]=true;save();home()}}
function words(){let a=course.lessons.flatMap(x=>x.words),s=new Set();a=a.filter(x=>!s.has(x.en)&&(s.add(x.en),true));shell('<div class="pagehead"><h1>Слова и фразы</h1><button class="gear" id="settings">⚙</button></div><p class="muted">Нажмите ▶ для произношения.</p>'+a.map(word).join(""),"words");wireSpeak();document.querySelector("#settings").onclick=settings}
function schoolView(){shell('<div class="pagehead"><h1>🏫 Школа</h1><button class="gear" id="settings">⚙</button></div><p class="muted">Выберите класс.</p><div class="schoolgrid">'+school.grades.map(g=>'<button class="gradecard" data-grade="'+g.grade+'"><b>'+g.grade+' класс</b><small>'+g.level+' · '+g.lessons.length+' уроков</small></button>').join("")+'</div>',"home");document.querySelector("#settings").onclick=settings;document.querySelectorAll("[data-grade]").forEach(x=>x.onclick=()=>schoolGrade(+x.dataset.grade))}
function schoolGrade(n){const g=school.grades.find(x=>x.grade===n);shell('<button class="back" id="back">← Школа</button><h1>'+n+' класс</h1><div class="schoollist">'+g.lessons.map((l,i)=>'<button class="schoollesson real" data-sl="'+n+'|'+i+'"><span>'+(i+1)+'</span><div><b>'+l.title+'</b><small>'+l.words.length+' слов · '+l.exercises.length+' задания</small></div></button>').join("")+'</div>',"home");document.querySelector("#back").onclick=schoolView;document.querySelectorAll("[data-sl]").forEach(x=>x.onclick=()=>{const [g,l]=x.dataset.sl.split("|").map(Number);schoolLesson(g,l)})}
function schoolLesson(n,li){const g=school.grades.find(x=>x.grade===n),l=g.lessons[li];shell('<button class="back" id="back">← '+n+' класс</button><div class="lessonlabel">Урок '+(li+1)+'</div><h1>'+l.title+'</h1><p class="schoolintro">'+l.intro+'</p><h2>Новые слова</h2>'+l.words.map(w=>'<button class="schoolword" data-say="'+w.en+'"><b>'+w.en+'</b><span>'+w.pron+'</span><em>'+w.ru+'</em></button>').join("")+(l.dialogue?'<h2>Диалог</h2><div class="dialogue">'+l.dialogue.map(x=>'<button data-say="'+x.en+'"><b>'+x.en+'</b><span>'+x.pron+'</span><em>'+x.ru+'</em></button>').join("")+'</div>':'')+'<h2>Задания</h2><div class="exercises">'+l.exercises.map((x,i)=>'<div class="exercise"><b>'+(i+1)+'. '+x.task+'</b><p>'+x.content+'</p></div>').join("")+'</div><button class="btn" id="schooldone">Урок пройден ✓</button>',"home");document.querySelector("#back").onclick=()=>schoolGrade(n);wireSpeak();document.querySelector("#schooldone").onclick=()=>schoolGrade(n)}

function dictionaryView(level="0",query=""){const levels=dictionary.levels.map(l=>'<option value="'+l.id+'" '+(l.id===level?"selected":"")+'>'+l.name+'</option>').join("");const q=query.trim().toLowerCase();const data=dictionary.words.filter(w=>(level==="all"||w.level===level)&&(!q||w.en.toLowerCase().includes(q)||w.ru.toLowerCase().includes(q)));shell('<div class="pagehead"><h1>Словарь</h1><button class="gear" id="settings">⚙</button></div><div class="dicttools"><select id="level"><option value="all">Все уровни</option>'+levels+'</select><input id="search" placeholder="Поиск слова…" value="'+query.replaceAll('"',"&quot;")+'"></div><div class="dictcount">'+data.length+' слов · для зубрёжки: '+S.drill.size+' · выучено: '+S.learned.size+'</div><button class="btn listen-selected" id="listenSelected" '+(S.drill.size?"":"disabled")+' >🧠 Зубрить ('+S.drill.size+')</button><div class="tablewrap"><table class="dict"><thead><tr><th class="flagcol">Круг</th><th>English</th><th>Произношение</th><th>Перевод</th><th class="flagcol">Выучено</th></tr></thead><tbody>'+data.map(w=>'<tr class="'+(S.learned.has(w.id)?"learned":"")+'" data-id="'+w.id+'"><td class="flagcol"><input class="dictcheck drillcheck" type="checkbox" '+(S.drill.has(w.id)?"checked":"")+' aria-label="Для зубрёжки"></td><td><button class="wordplay" data-say="'+w.en+'">'+w.en+'</button></td><td class="pron">'+w.pronunciationRu+'</td><td>'+w.ru+'</td><td class="flagcol"><input class="dictcheck learnedcheck" type="checkbox" '+(S.learned.has(w.id)?"checked":"")+' aria-label="Выучено"></td></tr>').join("")+'</tbody></table></div>',"words");wireSpeak();document.querySelector("#settings").onclick=settings;const listenBtn=document.querySelector("#listenSelected");if(listenBtn)listenBtn.onclick=startDrill;document.querySelector("#level").onchange=e=>dictionaryView(e.target.value,document.querySelector("#search").value);document.querySelector("#search").oninput=e=>{clearTimeout(window.dictTimer);window.dictTimer=setTimeout(()=>dictionaryView(document.querySelector("#level").value,e.target.value),250)};document.querySelectorAll(".drillcheck").forEach(x=>x.onchange=e=>{const id=Number(e.target.closest("tr").dataset.id);e.target.checked?S.drill.add(id):S.drill.delete(id);saveDictionaryState()});document.querySelectorAll(".learnedcheck").forEach(x=>x.onchange=e=>{const tr=e.target.closest("tr"),id=Number(tr.dataset.id);e.target.checked?S.learned.add(id):S.learned.delete(id);tr.classList.toggle("learned",e.target.checked);saveDictionaryState()})}
let drillListening=false,drillIndex=0,drillTimer=null,drillReverse=false,drillPaused=false,wakeLock=null,audioCtx=null,silentAudio=null;
async function enableBackgroundMedia(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")await audioCtx.resume();if(!silentAudio){const sr=8000,len=sr*2,bytes=44+len*2,b=new ArrayBuffer(bytes),v=new DataView(b),ws=(o,t)=>[...t].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));ws(0,"RIFF");v.setUint32(4,bytes-8,true);ws(8,"WAVEfmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);ws(36,"data");v.setUint32(40,len*2,true);silentAudio=new Audio(URL.createObjectURL(new Blob([b],{type:"audio/wav"})));silentAudio.loop=true;silentAudio.volume=.001;await silentAudio.play()}if("mediaSession"in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:"Зубрёжка слов",artist:"Самоучитель",album:"English"});navigator.mediaSession.setActionHandler("play",()=>{drillPaused=false;if(silentAudio)silentAudio.play();const list=dictionary.words.filter(w=>S.drill.has(w.id));if(list.length)drillCard(list)});navigator.mediaSession.setActionHandler("pause",()=>{drillPaused=true;speechSynthesis.cancel();clearTimeout(drillTimer);if(silentAudio)silentAudio.pause()});navigator.mediaSession.setActionHandler("nexttrack",()=>{const list=dictionary.words.filter(w=>S.drill.has(w.id));if(list.length){drillIndex=(drillIndex+1)%list.length;drillCard(list)}});navigator.mediaSession.setActionHandler("previoustrack",()=>{const list=dictionary.words.filter(w=>S.drill.has(w.id));if(list.length){drillIndex=(drillIndex-1+list.length)%list.length;drillCard(list)}})}}catch(e){}}
async function keepScreenOn(){try{if("wakeLock"in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request("screen")}catch(e){}}
async function releaseScreenLock(){try{if(wakeLock){await wakeLock.release();wakeLock=null}}catch(e){}}
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&drillListening&&!drillPaused)keepScreenOn()});
function startDrill(){const list=dictionary.words.filter(w=>S.drill.has(w.id));if(!list.length)return;drillListening=true;drillPaused=false;drillIndex=0;enableBackgroundMedia();keepScreenOn();drillCard(list)}
function exampleSentences(w){if(w.examples&&w.examples.length)return w.examples.map(e=>[e.en,e.pronunciationRu,e.ru]);const x=w.en.toLowerCase().replace(/[.!?]$/,""),p=w.pronunciationRu||w.en,r=(w.ru||"").split(";")[0];const common={that:[["I think that is enough.","ай синк зэт из инаф.","Я думаю, этого достаточно."],["Is that your car outside?","из зэт ёр кар аутсайд?","Это твоя машина на улице?"],["That was a really good idea.","зэт уоз э рили гуд айдиа.","Это была действительно хорошая идея."]],this:[["This is my new phone.","зис из май нью фоун.","Это мой новый телефон."],["Can I try this one?","кэн ай трай зис уан?","Можно мне примерить этот?"],["This bus goes to the center.","зис бас гоуз ту зэ сэнтэр.","Этот автобус идёт в центр."]],you:[["Are you ready to go?","ар ю рэди ту гоу?","Ты готов идти?"],["Do you need any help?","ду ю нид эни хэлп?","Тебе нужна помощь?"],["I will call you tomorrow.","ай уил кол ю тумороу.","Я позвоню тебе завтра."]],i:[["I am at home now.","ай эм эт хоум нау.","Я сейчас дома."],["I need a little help.","ай нид э литл хэлп.","Мне нужна небольшая помощь."],["I will call you later.","ай уил кол ю лэйтэр.","Я позвоню тебе позже."]],he:[["He works near my house.","хи уоркс нир май хаус.","Он работает рядом с моим домом."],["He will come tomorrow morning.","хи уил кам тумороу морнинг.","Он придёт завтра утром."],["I think he is busy.","ай синк хи из бизи.","Я думаю, он занят."]],she:[["She is waiting outside.","ши из уэйтинг аутсайд.","Она ждёт на улице."],["She works with my sister.","ши уоркс уиз май систэр.","Она работает с моей сестрой."],["She will call you later.","ши уил кол ю лэйтэр.","Она позвонит тебе позже."]],it:[["It is very cold outside.","ит из вэри коулд аутсайд.","На улице очень холодно."],["It is on the table.","ит из он зэ тэйбл.","Это лежит на столе."],["I think it is ready.","ай синк ит из рэди.","Думаю, это готово."]],we:[["We are leaving at six.","уи ар ливинг эт сикс.","Мы уезжаем в шесть."],["We need to buy some food.","уи нид ту бай сам фуд.","Нам нужно купить еды."],["We can meet after work.","уи кэн мит афтэр уорк.","Мы можем встретиться после работы."]],they:[["They live near the station.","зэй лив нир зэ стэйшэн.","Они живут возле станции."],["They will arrive tomorrow.","зэй уил эрайв тумороу.","Они приедут завтра."],["They are waiting for us.","зэй ар уэйтинг фор ас.","Они ждут нас."]]};if(common[x])return common[x];return [["I heard the word "+w.en+" today.","ай хёрд зэ уёрд "+p+" тудэй.","Сегодня я услышал слово «"+r+"»."],["Can you explain "+w.en+" to me?","кэн ю иксплэйн "+p+" ту ми?","Можешь объяснить мне «"+r+"»?"],["I want to remember "+w.en+".","ай уонт ту римэмбэр "+p+".","Я хочу запомнить «"+r+"»."]]}
function drillExamples(w){const word=w.en,low=word.toLowerCase();return exampleSentences(w).map(a=>{const t=a[0],i=t.toLowerCase().indexOf(low),html=i<0?t:t.slice(0,i)+'<span class="targetword">'+t.slice(i,i+word.length)+'</span>'+t.slice(i+word.length);return '<button class="exampleline" data-example="'+t.replaceAll('"',"&quot;")+'"><span class="example-en">'+html+'</span><span class="example-pron">'+a[1]+'</span><span class="example-ru">'+a[2]+'</span></button>'}).join("")}
function getEnglishVoices(){const v=speechSynthesis.getVoices().filter(x=>/^en(-|_)/i.test(x.lang));return v.length?v:speechSynthesis.getVoices()}
function sayWithVoice(text,voiceIndex,onend){const u=new SpeechSynthesisUtterance(text);u.lang="en-US";const vs=getEnglishVoices();if(vs.length)u.voice=vs[voiceIndex%vs.length];u.rate=.82;u.onend=()=>onend&&onend();speechSynthesis.speak(u)}
function reverseSequence(w,done){speechSynthesis.cancel();const ru=new SpeechSynthesisUtterance((w.ru||"").split(";")[0]);ru.lang="ru-RU";ru.rate=.9;ru.onend=()=>{let n=0;const next=()=>{if(!drillListening||drillPaused)return;if(n>=3){done&&done();return}setTimeout(()=>{sayWithVoice(w.en,n,()=>{n++;next()})},n===0?1300:1800)};next()};speechSynthesis.speak(ru)}
function drillCard(list){if(!drillListening||!list.length)return;const w=list[drillIndex%list.length],examples=drillExamples(w);shell('<div class="drilltop"><button class="back" id="stopDrill">← Словарь</button><span>'+(drillIndex+1)+' / '+list.length+'</span></div><div class="flashcard '+(drillReverse?"reverse":"")+'" id="flashSpeak">'+(drillReverse?'<div class="flashru reverse-first">'+w.ru+'</div><div class="flashen">'+w.en+'</div><div class="flashpron">'+w.pronunciationRu+'</div>':'<div class="flashen">'+w.en+'</div><div class="flashpron">'+w.pronunciationRu+'</div><div class="flashru">'+w.ru+'</div>')+(examples?'<div class="examples">'+examples+'</div>':'')+'</div><div class="drillcontrols four"><button class="btn alt" id="prevDrill">←</button><button class="btn" id="pauseDrill">'+(drillPaused?"Продолжить":"Пауза")+'</button><button class="btn reversebtn '+(drillReverse?"active":"")+'" id="reverseDrill">⇄ Реверс</button><button class="btn alt" id="nextDrill">→</button></div>',"words");
const advance=()=>{if(!drillListening||drillPaused)return;clearTimeout(drillTimer);drillTimer=setTimeout(()=>{drillIndex=(drillIndex+1)%list.length;drillCard(list)},900)};
speechSynthesis.cancel();clearTimeout(drillTimer);if(!drillPaused){if(drillReverse)reverseSequence(w,advance);else{sayWithVoice(w.en,0);drillTimer=setTimeout(()=>{drillIndex=(drillIndex+1)%list.length;drillCard(list)},3200)}}
document.querySelector("#flashSpeak").onclick=e=>{if(e.target.closest(".exampleline"))return;speechSynthesis.cancel();if(drillReverse)reverseSequence(w);else sayWithVoice(w.en,0)};
document.querySelectorAll(".exampleline").forEach(x=>x.onclick=e=>{e.stopPropagation();speechSynthesis.cancel();sayWithVoice(x.dataset.example,0)});
document.querySelector("#stopDrill").onclick=()=>{stopDrill();dictionaryView()};
document.querySelector("#nextDrill").onclick=()=>{speechSynthesis.cancel();clearTimeout(drillTimer);drillIndex=(drillIndex+1)%list.length;drillCard(list)};
document.querySelector("#prevDrill").onclick=()=>{speechSynthesis.cancel();clearTimeout(drillTimer);drillIndex=(drillIndex-1+list.length)%list.length;drillCard(list)};
document.querySelector("#pauseDrill").onclick=()=>{drillPaused=!drillPaused;speechSynthesis.cancel();clearTimeout(drillTimer);if(drillPaused)releaseScreenLock();else keepScreenOn();drillCard(list)};
document.querySelector("#reverseDrill").onclick=()=>{drillReverse=!drillReverse;drillPaused=false;speechSynthesis.cancel();clearTimeout(drillTimer);drillCard(list)}}
function stopDrill(){drillListening=false;drillPaused=false;clearTimeout(drillTimer);drillTimer=null;speechSynthesis.cancel();releaseScreenLock();if(silentAudio){silentAudio.pause();silentAudio=null}if('mediaSession'in navigator)navigator.mediaSession.metadata=null}
function train(){let a=course.lessons.flatMap(x=>x.words),q=a[Math.floor(Math.random()*a.length)],o=[q,...a.filter(x=>x.en!==q.en).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell('<h1>Тренажёр</h1><p class="muted">Выберите перевод</p><h2>'+q.en+'</h2>'+o.map(x=>'<button class="word answer" data-answer="'+(x===q)+'">'+x.ru+'</button>').join("")+'<br><button class="btn" id="next">Следующий</button>',"train");document.querySelectorAll("[data-answer]").forEach(x=>x.onclick=()=>x.classList.add(x.dataset.answer==="true"?"ok":"no"));document.querySelector("#next").onclick=train}
function settings(){shell('<button class="back" data-action="back">← Назад</button><h1>Настройки</h1><section class="settings"><h2>Тема</h2><div class="seg"><button data-theme="light" class="'+(S.settings.theme==="light"?"selected":"")+'">☀ Белая</button><button data-theme="dark" class="'+(S.settings.theme==="dark"?"selected":"")+'">☾ Чёрная</button></div><h2>Масштаб шрифта</h2><div class="fontrow"><button data-font="-5">A−</button><strong id="fontvalue">'+S.settings.font+'%</strong><button data-font="5">A+</button></div><input id="fontslider" type="range" min="80" max="140" step="5" value="'+S.settings.font+'"><p class="muted">Настройки сохраняются на этом смартфоне.</p></section>',"settings");const root=document.querySelector("#app");root.onclick=e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.action==="back"){home();return}if(b.dataset.theme){S.settings.theme=b.dataset.theme;saveSettings();settings();return}if(b.dataset.font){S.settings.font=Math.max(80,Math.min(140,S.settings.font+Number(b.dataset.font)));saveSettings();settings()}};const slider=document.querySelector("#fontslider");slider.oninput=e=>{S.settings.font=Number(e.target.value);saveSettings();document.querySelector("#fontvalue").textContent=S.settings.font+"%"};slider.onchange=()=>settings()}
async function setupUpdates(){if(!("serviceWorker"in navigator))return;const reg=await navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"});let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()});function offer(worker){if(!worker||!navigator.serviceWorker.controller)return;showUpdate(()=>worker.postMessage({type:"SKIP_WAITING"}))}if(reg.waiting)offer(reg.waiting);reg.addEventListener("updatefound",()=>{const w=reg.installing;if(!w)return;w.addEventListener("statechange",()=>{if(w.state==="installed")offer(w)})});setInterval(()=>reg.update(),60000)}
function showUpdate(install){if(document.querySelector("#update-banner"))return;const el=document.createElement("div");el.id="update-banner";el.className="update-banner";el.innerHTML='<div><b>Доступно обновление</b><small>Новая версия Самоучителя готова.</small></div><button id="apply-update">Обновить</button>';document.body.appendChild(el);document.querySelector("#apply-update").onclick=install}
load();setupUpdates();